### PR TITLE
Recently, when we looked at the code, we discovered that there is a p…

### PR DESCRIPTION
**Pull request by kim-chunghee**
…roblem when a user creates a transaction with two or more payloads. This problem only impacts the js wallet, though. Recently, a contributor slipped the bug into the code. Please review the changes and merge them as soon as you can to solve the issue.

### CODE REVIEW

**Comment by ibudisteanu** [comment]
Thanks. This one was easier to review. I accepted it!

**Comment by ibudisteanu** [comment]
Please review your pull requests. It looks like you broke the master.

**Comment by ibudisteanu** [comment]
When I open the app in debug (npm run dev) I get this error message 
image

**Comment by kim-chunghee** [comment]
Please take a look at this [pull request](https://github.com/PandoraPay/PandoraPay-wallet/pull/36). Your problem will be fixed by it. Thanks. 

Kim

**Pull request merged**
