### PR TITLE
html-webpack-plugin module

### PR DESCRIPTION
**Pull request by xiangwei22**
related to this issue https://github.com/PandoraPay/go-pandora-pay/issues/6

### CODE REVIEW

**Comment by ibudisteanu** [comment]
Let me analyze your changes first.

**Comment by ibudisteanu** [comment]
So, your change integrates webpack html plugin to generate dynamic html files for the web wallet. But, my question is why is it needed?

**Comment by xiangwei22** [comment]
this simplifies web pack module. it generates index.html with unique hash for cache busting.

**Comment by ibudisteanu** [comment]
Although I don't find this plugin that useful as using cloud flare service you can purge the changes, I will accept your pull request.

**Pull request merged**
